In [6]:
import cv2
import numpy as np

## Review section

In [46]:
img = cv2.imread('lena.jpg')
cv2.imshow('lenna', img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [5]:
# Gaussian Kernel Effect
# GaussianBlur(img,kernelsize,variance)
# 第二个参数应该是高斯核的大小，size.width and size.height
g_img = cv2.GaussianBlur(img,(7,7),5)
cv2.imshow('gaussian_blur_lenna', g_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [4]:
# 图像变更模糊，因为范围更大，平均效果更明显
g_img = cv2.GaussianBlur(img,(17,17),5)
cv2.imshow('gaussian_blur_lenna', g_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [6]:
# 图像更清晰，因为方差更小，高斯图像更尖锐，中心点起的作用更大
g_img = cv2.GaussianBlur(img,(7,7),1)
cv2.imshow('gaussian_blur_lenna', g_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [13]:
# 来看看高斯核
kernel = cv2.getGaussianKernel(7, 5)
print(kernel)

[[ 0.12895603]
 [ 0.14251846]
 [ 0.15133131]
 [ 0.1543884 ]
 [ 0.15133131]
 [ 0.14251846]
 [ 0.12895603]]


In [15]:
# 为啥一维，因为一维运算快
# 理论解释
# 用显式地代码看隐式地高斯和显示地分步高斯地效果
g1_img = cv2.GaussianBlur(img,(7,7),5)
g2_img = cv2.sepFilter2D(img, -1, kernel, kernel) 
# ori, depth, kernelX, kernelY
cv2.imshow('g1_blur_lenna', g1_img)
cv2.imshow('g2_blur_lenna', g2_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [16]:
######## Other Applications #########
# 2nd derivative: laplacian （双边缘效果）
kernel_lap = np.array([[0, 1, 0], [1, -4, 1], [0, 1, 0]], np.float32)
lap_img = cv2.filter2D(img, -1, kernel=kernel_lap)
cv2.imshow('lap_lenna', lap_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [17]:
# 应用： 图像锐化 = edge+ori
# app: sharpen
# 图像+edge=更锐利地图像，因为突出边缘
kernel_sharp = np.array([[0, 1, 0], [1, -3, 1], [0, 1, 0]], np.float32) 
lap_img = cv2.filter2D(img, -1, kernel=kernel_sharp)
cv2.imshow('sharp_lenna', lap_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [18]:
# 这样不对，因为，周围有4个1，中间是-3，
# 虽然有边缘效果，但是周围得1会使得原kernel有滤波效果，使图像模糊；
# 解决：所以取kernel_lap得相反数，再加上原图像，这样突出了中心像素，
#      效果类似于小方差的高斯，所以
#      可以既有边缘效果，又保留图像清晰度
kernel_sharp = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]], np.float32) 
lap_img = cv2.filter2D(img, -1, kernel=kernel_sharp)
cv2.imshow('sharp_lenna', lap_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [19]:
# 更“凶猛”的边缘效果
# 不仅考虑x-y方向上的梯度，同时考虑了对角线方向上的梯度
kernel_sharp = np.array([[1, 1, 1], [1, -8, 1], [1, 1, 1]], np.float32) 

In [20]:
######## Edge #########
# x轴
edgex = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]], np.float32)
sharp_img = cv2.filter2D(img, -1, kernel=edgex)
cv2.imshow('edgex_lenna', sharp_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [21]:
# y轴
edgey = np.array([[-1, 0, -1], [-2, 0, 2], [-1, 0, 1]], np.float32)
sharpy_img = cv2.filter2D(img, -1, kernel=edgey)
cv2.imshow('edgex_lenna', sharp_img)
cv2.imshow('edgey_lenna', sharpy_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [23]:
######### 角点 ###########
img = cv2.imread('lena.jpg')
img = cv2.resize(img, (640, 480))
img_gray = np.float32(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY))
print(img_gray)

[[ 169.  169.  169. ...,  180.  178.  178.]
 [ 169.  169.  169. ...,  181.  179.  179.]
 [ 168.  168.  169. ...,  182.  182.  182.]
 ..., 
 [  25.   25.   28. ...,   92.   93.   93.]
 [  24.   24.   27. ...,   97.   98.   98.]
 [  24.   24.   27. ...,   98.   99.   99.]]


In [24]:
img_harris = cv2.cornerHarris(img_gray, 2, 3, 0.05)    # 2： blockSize: window size; 3: Sobel kernel size
cv2.imshow('img_harris ', img_harris)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()
# 没法看原因：1. float类型； 2. img_harris本质上是每个pixel对于Harris函数的响应值
# 没有看的价值
print(img_harris)

[[ -4.34570294e-03  -4.34570294e-03   5.39062507e-02 ...,   9.85547066e-01
    1.94208488e+01   5.59296894e+00]
 [ -4.34570294e-03  -4.34570294e-03   5.39062507e-02 ...,   9.85547066e-01
    1.94208488e+01   5.59296894e+00]
 [  4.29687500e-02   4.29687500e-02   1.37500003e-01 ...,   1.10058107e+01
    2.41101074e+01  -2.74851570e+01]
 ..., 
 [  8.64448166e+00   8.64448166e+00  -1.51742668e+01 ...,  -1.04081335e+03
   -9.79503357e+02  -8.92338318e+02]
 [  3.73749995e+00   3.73749995e+00  -2.24179688e+01 ...,  -2.43200012e+02
   -2.22512497e+02  -2.16612503e+02]
 [  4.37500000e-01   4.37500000e-01  -3.37719231e+01 ...,   1.17999992e+01
    3.73749924e+00  -1.03625011e+01]]


In [28]:
# 为了显示清楚
# img_harris = cv2.dilate(img_harris , None)

In [27]:
thres = 0.05 * np.max(img_harris)
img[img_harris > thres] = [0, 0, 255]
cv2.imshow('img_harris ', img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [13]:
########### SIFT ###########
# img = cv2.imread('Week1/Cat.jpg')
img = cv2.imread('test001.jpg')
# create sift class
# one important thing for this function, we should use 3.4 version because the greater verison cann't support this function
# pip unstall python-opencv==3.3.0.10
# pip install python-contrib-opencv=3.3.0.10
# Older verison is better for opencv maybe
sift = cv2.xfeatures2d.SIFT_create()
# detect SIFT
kp = sift.detect(img,None)   # None for mask
# compute SIFT descriptor
kp,des = sift.compute(img,kp)
# print(des.shape)
img_sift= cv2.drawKeypoints(img,kp,outImage=np.array([]), flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
cv2.imshow('lenna_sift.jpg', img_sift)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

# Practice Time

In [1]:
# [Coding]:
# Finish 2D convolution/filtering by your self. 二维卷积/滤波
#   What you are supposed to do can be described as "median blur"（中间模糊）, which means by using a sliding window 
# on an image, your task is not going to do a normal convolution, but to find the median value within 
# that crop.（在sliding window中找出中间值）
#   You can assume your input has only one channel. (a.k.a a normal 2D list/vector)
#   And you do need to consider the padding method and size. There are 2 padding ways: REPLICA & ZERO. When 
# "REPLICA" is given to you, the padded pixels are same with the border pixels. E.g is [1 2 3] is your
# image, the padded version will be [(...1 1) 1 2 3 (3 3...)] where how many 1 & 3 in the parenthesis 
# depends on your padding size. When "ZERO", the padded version will be [(...0 0) 1 2 3 (0 0...)] 
#
#   Assume your input's size of the image is W * H, kernel size's m * n. You may first complete a version 
# with O(W·H·m·n log(m·n)) to O(W·H·m·n·m·n)).
#  Follow up 1: Can it be completed in a shorter time complexity?
#
#    Python version:
#    def medianBlur(img, kernel, padding_way):
#        img & kernel is List of List; padding_way a string
#        Please finish your code under this blank
#
#

## Testing section

In [3]:
import numpy as np
import copy
import cv2
from matplotlib import pyplot as plt
%matplotlib inline

In [36]:
# np.pad(array, padding_number, mode)
# numpy 自带的padding函数，可以为array自动填充边缘按照指定规则
# array 数组，可以是多维数组
# padding_number 填充的边缘数
# mode 默认是constant( constant 代表填充0，edge代表重复边缘)
a = np.arange(9)
print('1d - a:', a)
a = a.reshape((3,3))
print('2d - a:')
print(a)
np.pad(a,1,'edge')  

1d - a: [0 1 2 3 4 5 6 7 8]
2d - a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 0, 1, 2, 2],
       [0, 0, 1, 2, 2],
       [3, 3, 4, 5, 5],
       [6, 6, 7, 8, 8],
       [6, 6, 7, 8, 8]])

In [37]:
np.pad(a,1,'constant')

array([[0, 0, 0, 0, 0],
       [0, 0, 1, 2, 0],
       [0, 3, 4, 5, 0],
       [0, 6, 7, 8, 0],
       [0, 0, 0, 0, 0]])

In [54]:
np.pad(a,3,'constant')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 2, 0, 0, 0],
       [0, 0, 0, 3, 4, 5, 0, 0, 0],
       [0, 0, 0, 6, 7, 8, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [45]:
# Calculate the connection between padding number and kernel size 
# Shape of original image is w,h 
# if kernel shape is 3 * 3, padding is 1, output array is w,h
# if kernel shape is 3 * 3, padding is 2, output array is w+2,h+2
# if kernel shape is 3 * 3, padding is 3, output array is w+4,h+4
# if kernel shape is 5 * 5, padding is 1, output array is w-2,h-2
# if kernel shape is 5 * 5, padding is 2, output array is w,h
# 2*padding + 1 - kernel.shape
# so output array shape is w + kernel.w/2 - 1 + padding, h + kernel.h/2 - 1 + padding
kernel = np.arange(9)
kernel = kernel.reshape((3,3))
print(kernel.shape)

(3, 3)


In [39]:
# Testing Code(对test_img进行中值滤波)
test_img = np.arange(25)
test_img = test_img.reshape((5,5))
test_img = cv2.imread('lena.jpg',0) 
print(test_img)

[[169 171 173 ..., 168 186 178]
 [168 170 171 ..., 163 179 186]
 [166 167 168 ..., 127 103  99]
 ..., 
 [ 31  37  27 ...,  49  62  66]
 [ 26  36  24 ...,  63  84  88]
 [ 24  36  24 ...,  71  96  99]]


In [40]:
padding_img = np.pad(test_img,1,'constant')
print(padding_img)
np.median(padding_img[0:0+3,0:0+3])
print(padding_img[1:1+3,1:1+3])
print(np.median(padding_img[1:1+3,1:1+3]))
result_list= [item for sublist in padding_img[0:0+3,0:0+3] for item in sublist]

[[  0   0   0 ...,   0   0   0]
 [  0 169 171 ..., 186 178   0]
 [  0 168 170 ..., 179 186   0]
 ..., 
 [  0  26  36 ...,  84  88   0]
 [  0  24  36 ...,  96  99   0]
 [  0   0   0 ...,   0   0   0]]
[[169 171 173]
 [168 170 171]
 [166 167 168]]
169.0


In [41]:
h, w = test_img.shape
print('h, w:',test_img.shape)
padding_size = 1
kh = 3
kw = 3
ow = w + 2 * padding_size + 1 - kw
oh = h + 2 * padding_size + 1 - kh
print('ow,oh:',ow,oh)
output_img = np.zeros((oh, ow))
for i in range(oh):# for column
    for j in range(ow):# for row
        output_img[i][j] = np.median(padding_img[i:i + kh, j:j + kw])
print(output_img)

h, w: (200, 200)
ow,oh: 200 200
[[   0.  169.  170. ...,  128.  168.    0.]
 [ 167.  169.  170. ...,  129.  168.  103.]
 [ 165.  167.  167. ...,  127.  103.   20.]
 ..., 
 [  31.   32.   36. ...,   41.   62.   42.]
 [  26.   27.   35. ...,   62.   71.   66.]
 [   0.   24.   24. ...,   42.   71.    0.]]


In [42]:
cv2.imshow('output_img', output_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [58]:
img = cv2.imread('test001.jpg')
print(len(img.shape))

3


In [64]:
np.arange(8).reshape((2,4)).shape

(2, 4)

## Coding

In [49]:
import numpy as np
import copy
import cv2
from matplotlib import pyplot as plt
%matplotlib inline

def medianBlur(img, kernel, padding_way, padding_size = 1):
    h, w = img.shape
    kh, kw = kernel.shape
    print('h, w:',img.shape)
    print('kh, kw:',kernel.shape)
    if padding_way == 'REPLICA':
        padding_img = np.pad(img, padding_size, 'edge')
    elif padding_way == 'COPY':
        padding_img = np.pad(img, padding_size, 'constant')
    ow = w + 2 * padding_size + 1 - kw
    oh = h + 2 * padding_size + 1 - kh
    print('ow,oh:',ow,oh)
    output_img = np.zeros((oh, ow))
    for i in range(oh):# for column
        for j in range(ow):# for row
            output_img[i][j] = np.median(padding_img[i:i + kh, j:j + kw])
    return output_img.astype("uint8")

In [50]:
img = cv2.imread('lena.jpg',0) 
cv2.imshow('img', img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [55]:
kernel = np.arange(9).reshape((3,3))
padding_way = 'COPY'
output_img = medianBlur(img, kernel, padding_way, padding_size = 1)
print(output_img)
cv2.imshow('img', img)
cv2.imshow('output_img', output_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

h, w: (200, 200)
kh, kw: (3, 3)
ow,oh: 200 200
[[  0 169 170 ..., 128 168   0]
 [167 169 170 ..., 129 168 103]
 [165 167 167 ..., 127 103  20]
 ..., 
 [ 31  32  36 ...,  41  62  42]
 [ 26  27  35 ...,  62  71  66]
 [  0  24  24 ...,  42  71   0]]


## Other reference

In [53]:
#one_extend函数实现2D图像的近值扩充,两边只分别扩充一个单元,要对外扩充多个单元，只需反复使用这个函数
def extend(img,padding_way):
    m,n=img.shape
    img_one_extend=np.zeros((m+2,n+2))
    img_one_extend[1:m+1,1:n+1]=img
    if padding_way=="ZERO":
        return img_one_extend
    elif padding_way=="REPLICA":
        img_one_extend[0][1:1+n]=img[0]
        img_one_extend[m+1][1:1+n]=img[m-1]
        img_one_extend[:,0]=img_one_extend[:,1]
        img_one_extend[:,n+1]=img_one_extend[:,n]
        img_one_extend=img_one_extend.astype('int')
        return img_one_extend
    else:
        print("Please input right padding_way")
    
#img_kernel函数实现一个2D图像,跟一个kernel*kernle的卷积核卷积的结果
def img_kernel(srcimg,kernel,padding_way):
    extend_index=int(kernel/2)
    img=copy.deepcopy(srcimg)
    for k in range(extend_index):
        img=extend(srcimg,padding_way)
    m,n=img.shape
    for i in range(int(kernel/2),m-int(kernel/2)):
        for j in range(int(kernel/2),n-int(kernel/2)):
            a=[]
            #print(img[i,j])
            a.append(img[i,j])
            a.append(img[i+1,j])
            a.append(img[i-1,j])
            a.append(img[i,j+1])
            a.append(img[i,j-1])
            a.append(img[i-1,j-1])
            a.append(img[i+1,j+1])
            a.append(img[i-1,j+1])
            a.append(img[i+1,j-1])
            a.sort()
            img[i,j]=a[int(len(a)/2)]    
    result=img[int(kernel/2):m-int(kernel/2),int(kernel/2):n-int(kernel/2)]                     
    return  result.astype("uint8")

In [54]:
src=cv2.imread("lena.jpg",0)
a=img_kernel(src,5,"REPLICA")
cv2.imshow("result",a)
k=cv2.waitKey()
if k==27:
    cv2.destroyAllWindows()